# Copyright 2024-2026 NXP
# NXP Proprietary.
# This software is owned or controlled by NXP and may only be used strictly in
# accordance with the applicable license terms. By expressly accepting such
# terms or by downloading, installing, activating and/or otherwise using the
# software, you are agreeing that you have read, and that you agree to comply
# with and are bound by, such license terms. If you do not agree to be bound
# by the applicable license terms, then you may not retain, install, activate
# or otherwise use the software.
import os.path
import sys
from dataclasses import dataclass, field


def get_onnxruntime_lib_path():
    """Get ONNX Runtime library path with dynamic Python version"""
    python_version = f"{sys.version_info.major}.{sys.version_info.minor}"
    return f"/usr/lib/python{python_version}/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so"


@dataclass
class Config:
    # Interfaces
    neutron_fw_path: str = "/usr/lib/firmware/NeutronFirmware.elf"

    ort_lib_path: str = get_onnxruntime_lib_path()
    tests_data_path: str = "tests/data"
    benchmark_questions_file: str = "tests/data/questions.txt"
    update_global_benchmark_json: bool = False

    # Messages
    prompt = "Please type your question:"
    start_kasr = "Press Enter to start Speech To Text"
    start_vasr = "Speak the wakeword to start"
    start_kasr_info = f"\n##### {start_kasr} #####"
    start_vasr_info = f"\n##### {start_vasr} #####"
    listening_info = "I'm listening!"
    tts_start_text: str = "Hello, I am your eIQ Gen AI Flow assistant, how can I help you?"
    out_of_domain_response_list = ["I'm sorry, but I can't help with that request.",
                                   "I'm unable to assist you with this topic.",
                                   "I cannot provide details on that subject."]
    ambiguous_response_list = ["Can you please reformulate?",
                               "Could you clarify your question?",
                               "Could you make your question clearer?"]

    # Parameters
    similarity_threshold: float = 0.65  # Minimum value of similarity for not considering the question ambiguous

    # Audio recording
    save_audio_capture: bool = False
    save_audio_playback: bool = False
    save_audio_vit: bool = False
    audio_save_path: str = "tests/recordings/"

    # Audio Playback
    keep_playback_device_open: bool = True  # Keep playback device always open for minimal latency

    # Audio Capture
    keep_capture_device_open: bool = False  # Keep capture device always open (False = open only when VIT/ASR active)

    # Notification when tts is going to talk
    play_tts_start_sound: bool = True

    # audio fillers (generated by the TTS)
    play_audio_filler: bool = False
    audio_filler_path: str = "assets/fillers"
    audio_filler_sentences = ["Okay.", "Got it.", "Alright.", "Let’s see.", "One moment.", "Just a second.", ]

    # Notification when wake word is detected
    play_wake_word_detect_sound: bool = True

    # Notification when intent is detected
    play_intent_detect_sound: bool = True

    # Benchmark settings
    silent_benchmark: bool = True  # Disable TTS playback and notifications during benchmark mode

    # Default args
    default_system_prompt: str = "Helpful assistant."

    # Debug
    python_packages_versions_to_display = ["onnxruntime", "transformers", "numpy", "torch", "accelerate",
                                           "optimum", "posix-ipc", "silero-vad"]

    # TTS settings
    tts_mode: str = "streaming"  # Options: "streaming", "default"

    # CPU settings
    set_cpu_governor: bool = True
    cpu_governor: str = "performance"
    restore_cpu_governor_on_exit: bool = True

    # VIT parameters
    wake_model_path: str = "vit/src/vit/models/VIT_Model_en.bin"
    vit_channel_indices: list = field(default_factory=lambda: [0])

    # STT (ASR) parameters
    stt_channel_indices: list = field(default_factory=lambda: [0])

    # RAG parameters
    rag_database_name: str = "rag_database.pkl"
    rag_database_path: str = os.path.join(os.path.dirname(__file__), "rag", "src", "data", rag_database_name)

    @dataclass
    # LLM parameters (do no set to use model-specific defaults)
    class LLMConfig:
        temperature: float  # Sampling temperature for randomness
        top_k: int  # Top-k sampling parameter
        top_p: float  # Top-p (nucleus) sampling parameter
        min_p: float  # Min-p sampling parameter
        repetition_penalty: float  # Penalty for repeating tokens
        end_margin: int = 18  # End margin for generation
        max_tokens_to_keep: int = 128  # Maximum tokens to keep for LLM generation
