[project]
name = "eiq_genai_flow"
dynamic = ["version"]
description = "Project integrating VIT wake word detection, Voice Identification (Voice ID), Speech-to-Text (STT), Retrieval-Augmented Generation (RAG), Large Language Models (LLMs), and Text-to-Speech (TTS)."
readme = "README.md"
authors = [
    { name = "NXP AI Software Team", email = "voice@nxp.com" }
]
license = "LicenseRef-LA-OPT-Online-Code-Hosting-NXP-Software-License-v1.4-May-2025"
license-files = ["LICENSE"]

# Main runtime dependencies
dependencies = [
    "transformers==5.12.1",
    "numpy>=2.4.3,<3.0.0",
    "posix_ipc==1.3.2",
    "psutil==7.2.2",
    "colorama==0.4.6",
    "accelerate==1.14.0",
    "typer==0.24.0",
    "tokenizers==0.22.2",
    "torch==2.12.1",
    "soundfile==0.14.0",
    "charset_normalizer>=3.4.7",
    "nxp_eiq_shared_utils",
    "nxp_eiq_text_to_speech",
    "nxp_eiq_speech_to_text",
    "nxp_eiq_audio_manager",
    "nxp_eiq_vit_wake_word",
    "nxp_eiq_llm",
    "nxp_eiq_vad",
    "nxp_eiq_voice_id",
    "nxp_eiq_retriever",
]

# Optional dependencies (for development)
[project.optional-dependencies]
dev = [
    "tenacity==8.3.0",
    "pandas==2.2.3",
    "altgraph==0.17.4",
]
gui = [
    "nxp_eiq_chat_interface",
]
onnxruntime = ["onnxruntime>=1.22"]

[project.urls]
Homepage = "https://www.nxp.com/design/design-center/software/embedded-software/eiq-genai-flow-conversational-ai-software-pipeline-on-edge-devices:GEN-AI-FLOW"

[build-system]
requires = ["setuptools>=67"]
build-backend = "setuptools.build_meta"

[project.scripts]
eiq_genai_flow = "eiq_genai_flow.__main__:main"
