[project]
name = "rag"
version = "0.2.0"
description = "Retrieval-Augmented Generation project compliant with the LLM Pipeline project."
authors = [
    {name = "Enzo Ruedas", email = "enzo.ruedas@nxp.com"},
]
readme = "README.md"
license-files = ["License"]

# Main runtime dependencies
dependencies = [
    "typer",
    "torch==2.7.1",
    "colorama==0.4.6",
    "transformers>=4.49.0",
    "onnx==1.18.0",
    "scikit-learn==1.7.0",
    "numpy==1.26.4; python_version <= '3.12'",
    "numpy==2.2.3; python_version >= '3.13'",
    "onnxruntime==1.20.1; python_version <= '3.12'",
    "onnxruntime==1.22.0; python_version >= '3.13'"
]

# Optional dependencies (for development)
[project.optional-dependencies]
dev = [
    "docling==2.32.0",
    "langchain-text-splitters==0.3.2",
    "spacy==3.8.7",
    "nltk==3.9.1",
    "accelerate==1.7.0",
    "datasets==3.2.0",
    "sentencepiece==0.2.0",
    "pytest==8.3.5",
    "jupyter==1.1.1",
    "nbmake==1.5.5",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.distutils.egg_info]
egg_base = "."

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "ERROR"
filterwarnings = [
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.setuptools.packages.find]
where = ["src", "src/rag/preprocessing"]