[project]
name = "chat_interface"
version = "1.0.0"
description = "Simple Graphical User Interface for eIQ GenAI Flow"

readme = "README.md"

# Main runtime dependencies
dependencies = [
    "posix_ipc==1.1.1",
    "PyQt6==6.9.1",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.distutils.egg_info]
egg_base = "."

[tool.setuptools.packages.find]
where = ["src"]
