[project]
name = "vit"
version = "1.0.0"
description = "Voice Intelligent Technology."
readme = "README.md"
authors = [
    {name = "Sebastien Chereau", email = "sebastien.chereau@nxp.com"}
]
dependencies = [
    "Cython==3.2.1",
    "pyalsaaudio==0.11.0",
    "soundfile==0.13.1",
    "colorama==0.4.6",
    "requests",
    "tqdm",
    "numpy==2.2.3; python_version >= '3.13'",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.distutils.egg_info]
egg_base = "."

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.setuptools.packages.find]
where = ["src", "src/shared_utils"]

